### ISSUE TITLE
Update khartec references in pom.xml

### ISSUE THREAD

**Issue by mcleo-d** [finos/waltz#4987]
### Description

The following _// cc @maoo for further support if required._ references where found in the `pom.xml` files below and should be changed to reflect **Waltz** in **FINOS**.

**https://github.com/finos/waltz/blob/master/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/pom.xml#L24)
- [x] [`<url>http://khartec.com</url>`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/pom.xml#L41)

**https://github.com/finos/waltz/blob/master/waltz-schema/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/waltz-schema/pom.xml#L25)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/waltz-schema/pom.xml#L56)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/waltz-schema/pom.xml#L60)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/waltz-schema/pom.xml#L64)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/waltz-schema/pom.xml#L68)
- [x] [`<packageName>com.khartec.waltz.schema</packageName>`](https://github.com/finos/waltz/blob/c50e52ad4638d13ea507955aaa0397fa563d93b1/waltz-schema/pom.xml#L150)

**https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml#L25)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml#L56)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml#L60)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml#L64)
- [x] [`See https://github.com/khartec/waltz/blob/master/docs/development/build.md for more information`](https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml#L68)
- [x] [`<packageName>com.khartec.waltz.schema</packageName>`](https://github.com/finos/waltz/blob/c6ec9261833437826824e87e4903452ea9439df3/waltz-schema/pom.xml#L150)

**https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-ng/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-ng/pom.xml#L25)

**https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-data/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-data/pom.xml#L25)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-data/pom.xml#L34)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-data/pom.xml#L40)

**https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-local-config/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-local-config/pom.xml#L25)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-local-config/pom.xml#L34)

**https://github.com/finos/waltz/blob/0cd49f70b1528d43867e90bdcf14aebca80f1a87/waltz-integration-test/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/0cd49f70b1528d43867e90bdcf14aebca80f1a87/waltz-integration-test/pom.xml#L25)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/0cd49f70b1528d43867e90bdcf14aebca80f1a87/waltz-integration-test/pom.xml#L34)

**https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-jobs/pom.xml**
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-jobs/pom.xml#L48)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-jobs/pom.xml#L76)
- [x] [`~ Copyright (c) 2015. Khartec Ltd.`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-jobs/pom.xml#L39)

**https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-model/pom.xml**
- [x] [`~ Copyright (c) 2015. Khartec Ltd.`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-model/pom.xml#39)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-model/pom.xml#48)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-model/pom.xml#58)

**https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-service/pom.xml**
- [x] [`~ Copyright (c) 2015. Khartec Ltd.`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-service/pom.xml#39)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-service/pom.xml#48)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-service/pom.xml#59)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/75e45ba063784fa604c4251f3f7512c2a7cca40d/waltz-service/pom.xml#65)

**https://github.com/finos/waltz/blob/dfd7c86712bd8d16c00ccb2eb930b9d3b9a0f005/waltz-common/pom.xml**
- [x] [`~ Copyright (c) 2019. Khartec Ltd.`](https://github.com/finos/waltz/blob/dfd7c86712bd8d16c00ccb2eb930b9d3b9a0f005/waltz-common/pom.xml#39)
- [x] [`<groupId>com.khartec</groupId>`](https://github.com/finos/waltz/blob/dfd7c86712bd8d16c00ccb2eb930b9d3b9a0f005/waltz-common/pom.xml#48)

_// cc @maoo for further support if required._

**Comment by davidwatkins73** [comment]
The entire codebase at should shift over to `org.finos`  (currently `com.khartec`).  Having a `pom.xml` group id and a package structure at odds with each other is probably not a good long-term idea

**Comment by davidwatkins73** [comment]
Taken us a while, but we have now moved over the entire code base from `com.khartec` to `org.finos`.

**Comment by davidwatkins73** [comment]
See accompanying [blog post](https://waltz.finos.org/blog/waltz/dev/2021/11/04/package-rename.html)
