### ISSUE TITLE
Grid To Roadmap diagram (PoC)

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#5130]
- [x]  Cloud dashboard
  - [x] change rating scheme for data taxonomy
  - [x] Font color should be complement of rating color
  - [x] show filter / stat for 'no rating'
- [ ] Cloud Roadmap Viz
   - [x] Integrate PoC into Waltz section
   - [x] Add strategy buckets 
   - [ ] Rating filters (similar to grid)
     - [ ] Possibly pre-canned filters (e.g Phase 1 = Retire & Phases 2 = Rehost | Replatform | etc)
   - [x] Sizing strategy
     - [ ] Colouring strategy
   - [x] **Strict range bands** 
      - not really strict, but `forceY().strength()` seems to help constrain the points
   - [x] Width/Height should be responsive
   - [ ] Loading indicator
   - [x] **still suffering sporadic performance issues**
     - clues: seems related to measurable inclusion
   - [x] **popover placement incorrect when used in full Waltz page**
   - [ ] search/highlight app
   - [ ] perf tune the js
   - [ ] allow fixed dates for milestones
   - [ ] dynamic number of milestones (think this is ok now, it's just the data generator which assumes a fixed number)

**Comment by davidwatkins73** [comment]
Perf seems to be fixed by updating `com.khartec.waltz.data.report_grid.ReportGridDao`, line 293,   to:

```[java]
 dsl
    .resultQuery(dsl.renderInlined(qry))
```

**Comment by davidwatkins73** [comment]
popover placements fixed by switching to `postion: fixed` and using `event.screenX, event.screenY` for coords.
