### ISSUE TITLE
Custom roles list needs search and scroll region

### ISSUE THREAD

**Issue by davidwatkins73** [finos/waltz#6057]
The _custom role admin_ section in Waltz (nav: `Profile > System Admin > Custom roles`) shows a long table with no simple way to search through the list.  

The form to **add** custom roles is underneath the table and so is hidden to to the non-experienced user and also forces all users to have to scroll to the end of the (potentially large) table.

To fix these issues we could add a scroll region around the table (search for usages of the html class `waltz-scroll-region-<size>`) and add a simple search field.  

The search could be implemented as a simple angular filter (e.g. `ng-repeat="row in $ctrl.rows | filter:qry"`, or by using the more flexible `termSearch` utility function (should be plenty of usage examples scattered across the code-base).

**Task list**
- [x] add scroll region
- [x] add search

**Extra**
- [x] Custom roles list doesn't refresh 
- [x] Form needs clearing after saving

**Comment by msagi** [comment]
Hi @davidwatkins73, I can give this a try 😃

**Comment by davidwatkins73** [comment]
Ooops, accidently closed prematurely.  Needs testing and releasing.

**Comment by davidwatkins73** [comment]
Hi @msagi ,
Just a quick note to say that this was rolled into the 1.47.2 release (which just went live).  
Thanks again for the contribution.
